
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xlqtqctjfwpuaihbvdkg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhscXRxY3RqZndwdWFpaGJ2ZGtnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc4NTYxNjksImV4cCI6MjA2MzQzMjE2OX0.6aHXgwR7v1bgZ16Ysd6FHDHuq_H68y2S-v3xyBIr5L0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});
